# Generated by Django 4.0.2 on 2023-08-20 23:20

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Avowal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "EN"), ("es", "ES")], default="en", max_length=2
                    ),
                ),
                (
                    "type_topic",
                    models.CharField(
                        choices=[
                            ("academic", "🎓  - Academic"),
                            ("job", "💼  - Job"),
                            ("family", "🤲  - Family"),
                            ("love", "❤️  - Love"),
                            ("sex", "🔥  - Sex"),
                            ("personal", "⚱️  - Personal"),
                            ("politics", "🌎  - Politics"),
                        ],
                        default="academic",
                        max_length=8,
                    ),
                ),
                (
                    "public_identifier",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("body", models.CharField(max_length=240)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            bases=(models.Model, core.models.HashidIdentifier),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.CharField(max_length=120)),
                (
                    "public_identifier",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "avowal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.avowal",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(models.Model, core.models.HashidIdentifier),
        ),
    ]
