# Generated by Django 4.0.2 on 2023-08-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avowal",
            name="language",
        ),
    ]
